
name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        version: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: adopt
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
