
name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        version: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: adopt
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package '-Djacoco.skip=true'
      - name: Upload importer-jar-with-dependencies.jar
        uses: actions/upload-artifact@v3
        with:
          name: importer-java${{ matrix.version }}-${{ matrix.os }}.jar
          path: polygon2pcms-console/target/importer-jar-with-dependencies.jar

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests
        run: mvn -B verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
