
name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: adopt
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: adopt
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
